# Housing inflation test : Z_test , Rejection Region

In [3]:
import pandas as pd
import numpy as np

In [4]:
#H_o=inflation of house is 10
#H_a=that it is greater than 10

In [5]:
# df of sample data contain 100 items
df=pd.read_csv("chapter10_assets/3_z_test_housing_inflation/house_price_increase.csv")
df.head()

  house_id  price_increase_pct
0    NJ001                12.7
1    NJ002                11.3
2    NJ003                11.9
3    NJ004                13.2
4    NJ005                12.8

In [6]:
df.shape

(100, 2)

In [7]:
# Given data, i.e population_mean, population_std_dev
population_mean=10
population_std=4

In [8]:
sample_mean=df["price_increase_pct"].mean()
sample_mean

11.0

In [9]:
# calculating standard error ,, i.e population_std/sqrt(sample size)

In [11]:
standard_error=population_std/np.sqrt(df.shape[0])
standard_error

0.4

In [12]:
z_score=(sample_mean-population_mean)/standard_error
z_score

2.5

In [13]:
alpha = 0.05 # significance level i.e alpha

In [14]:
from scipy import stats
z_critical=stats.norm.ppf(1-alpha)
z_critical

1.6448536269514722

In [15]:
z_score,z_critical

(2.5, 1.6448536269514722)

-Since z_score > z_critical , i.e fall in rejection region , hence we will reject the 
-Null Hypothesis. This means alternate hypothesis becomes true which means the inflation-of 
-house is greater than 10%

# Z_test using P_value

In [16]:
# cumulative percentage for z_score 2.5
stats.norm.cdf(z_score)

0.9937903346742238

In [17]:
# caclulating p_value from z_score percentage
p_value=1-stats.norm.cdf(z_score)
p_value

0.006209665325776159

In [18]:
p_value,alpha

(0.006209665325776159, 0.05)

-Since P_value (0.006) is less than alpha (i.e significance level 0.05) , hence we reject the null hypothesis. This means there is statistically significant evidence to support the claim that the inflation rate in house prices is higher than the reported 10%

In [19]:
1-stats.norm.cdf(1.5)

0.06680720126885809

# A/B Testing : Drug Trial

In [20]:
df_control=pd.read_csv("chapter10_assets/11_z_test_AB_testing_coding/control_group.csv")
df_control.head()

  person_id  recovery_time_hrs
0      C001                4.4
1      C002                4.1
2      C003                3.2
3      C004                4.3
4      C005                4.9

In [21]:
df_test=pd.read_csv("chapter10_assets/11_z_test_AB_testing_coding/test_group.csv")
df_test.head()

  person_id  recovery_time_hrs
0      T001                3.7
1      T002                4.1
2      T003                3.7
3      T004                3.9
4      T005                3.7

In [22]:
df_control["recovery_time_hrs"].mean()

4.000769230769231