In [1]:
import pandas as pd
from matplotlib import pyplot as plot

In [2]:
df=pd.read_csv("shoe_sales.csv")
df.head()

       date   brand  sold_qty
0  9/1/2023    Nike      24.0
1  9/1/2023  Adidas      14.0
2  9/2/2023    Nike      21.0
3  9/2/2023  Adidas      12.0
4  9/3/2023    Nike      18.0

In [4]:
 df.shape

(60, 3)

In [5]:
df.describe()

         sold_qty
count   58.000000
mean    27.482759
std     88.519844
min      7.000000
25%     12.250000
50%     16.000000
75%     19.750000
max    689.000000

In [7]:
df[df["sold_qty"]<12.25].shape # 25% of 60

(15, 3)

### 1. Nike Analysis

In [9]:
df_nike=df[df["brand"]=="Nike"]
df_nike.shape

(30, 3)

In [10]:
df_nike.describe()

        sold_qty
count  28.000000
mean   19.642857
std     3.117624
min    14.000000
25%    17.000000
50%    19.500000
75%    22.000000
max    25.000000